<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
 <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	
    <NoWarn>$(NoWarn);CS8602</NoWarn>
	
    <ApplicationIcon>logo.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Img\logo-300 1.png" />
    <None Remove="Img\MagnifyingGlass.png" />
    <None Remove="Img\PaperPlaneRight.png" />
    <None Remove="Img\SidebarSimple.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Img\PaperPlaneRight.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Content Include="logo.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Img\logo-300 1.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Img\MagnifyingGlass.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Img\SidebarSimple.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="HandyControl" Version="3.5.1" />
    <PackageReference Include="MarkdView" Version="1.0.11" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Model\" />
    <Folder Include="Api\" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Windows.Forms">
      <HintPath>C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\System.Windows.Forms.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
